### ISSUE TITLE
Behavior of space bar interruption on Assignment 1

### ISSUE THREAD

**Issue by brunofavs** [miguelriemoliveira/psr_22-23#1]
Say a player starts a test in non timed mode, types 5 out of 10 letters for instance, then breaks out using the space key.
We're assuming the player should still be getting statistics on the letters he actually typed.

Thing is, lets say the player took 5 seconds to type the first 5 shown keys, then upon being shown the 6th key, took half an hour to eventually break with the space bar.

We're undecided on what the program should actually do : 
  1.  Should the 'test duration' be only 5 seconds and all the statistics based on the 5 seconds he took to type 5 keys;

  2.  Should the 'test' duration actually be 30min5s and all the statistics still be based on the 5 seconds so that statistic would still be reasonable;
  3. Should the 'test duration' be 30min5s and all statistic be based on the whole 30min5s and make it so all statistics are unmatched of those of a typical human. This way theoretically the player would've taken an average of **30min5s / types** seconds to type each key.

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

I think you can choose any alternative. We know that if the test was interrupted,  some statistics may be poluted, so its not a big deal.

**Comment by brunofavs** [comment]
Hi,
Ok good to know, then we'll go with the first one as its already implemented. This way the only mildly incorrect statistic is the test duration.
Thanks!
