### ISSUE TITLE
Problem with launching the objects in the gazebo map

### ISSUE THREAD

**Issue by MojganGhanbari** [miguelriemoliveira/psr_22-23#14]
Hi,
I am using Ubuntu 20.04.5 LTS , 
I am trying to launch gazebo.launch, I have the figure of apartment map without objects and it is not similar to professor's figure in the trabalho3. I followed the steps of professor's class and I entered this command "roslaunch robutler_bringup gazebo.launch" and I got the map that I attached. Now I would like to know is it right and what should I do?
thanks

![default_gzclient_camera(1)-2023-01-25T11_36_37 112306](https://user-images.githubusercontent.com/115163879/214828402-413de2f3-dbde-4e8c-8575-be93ad0338c2.jpg)

**Comment by miguelriemoliveira** [comment]
Hi @MojganGhanbari ,

Two possible ways of solving the problem:

1. It may be that you did not git clone the aws repositories as detailed here:

https://github.com/miguelriemoliveira/psr_22-23/tree/master/Parte12#exerc%C3%ADcio-8---utiliza%C3%A7%C3%A3o-do-psr_apartment-como-world

2. If that does not work the solution is to add your own objects to gazebo and then save a new world. The procedure is described here:
https://github.com/miguelriemoliveira/psr_22-23/issues/12

Let me know if you have any questions.

**Comment by MojganGhanbari** [comment]
Thank you Professor, I solved it by the first way.
