### ISSUE TITLE
Erro ao lançar o psr_apartment.world 

### ISSUE THREAD

**Issue by jgvf** [miguelriemoliveira/psr_22-23#15]
Na aula gravada "Aula 11 P2 (EN) - PSR 2022-2023", já para o final foi-me aconcelhado a copiar a pasta psr_apartment_description para a pasta "Parte12" e no ficheiro gazebo.launch modar o mapa.

![Screenshot from 2023-01-27 22-20-07](https://user-images.githubusercontent.com/116443385/215224876-1e2ee4d9-1efb-4548-9ec0-13ee31d36af6.png)

 E na verificação das novas alterções está a dar um erro.
 
![Screenshot from 2023-01-27 22-20-31](https://user-images.githubusercontent.com/116443385/215224811-6177dd58-7abc-4611-af44-99ad5f88858a.png)

O erro está no camiho para chegar ao prs_apartment.world, na alteração que fiz?Como posso resolver este problema?

**Comment by miguelriemoliveira** [comment]
Olá @jgvf ,

na primeira imagem você comentou a  linha 3, substituindo-a pela 4.

Na verdade a linha 3 estava bem, e o que você tinha de alterar era a linha 5, apontando para o world do psr apartment.

Se em vez de copiar as imagens, copiar o texto do código desta forma 

```python
def main():
    print('Hello')
```

Eu posso ajudar melhor porque consigo copiar e alterar ...
