### ISSUE TITLE
Gazebo World sem os Models todos apresentados na aula

### ISSUE THREAD

**Issue by xico25** [miguelriemoliveira/psr_22-23#16]
Boa tarde professor , 
Ao dar launch do world que esta no repositorio psr_descripiton_apartment aulas apenas são apresentados alguns models . 
Foi feito de ante-mão o clone dos repositorios pedidos nos tutoriais das aulas e o compile do catkin_ws.
Alguma sugestão? 
![Captura de ecrã de 2023-01-28 15-26-22](https://user-images.githubusercontent.com/114620663/215274882-a3a1d0f3-082a-4a9a-816d-9d164b98fe4b.png)

**Comment by miguelriemoliveira** [comment]
Olá @xico25 . Você fechou o issue. Já resolveu?

**Comment by xico25** [comment]
@miguelriemoliveira De certa forma , de acordo com a resolução dada no issue 12 , poemos decorar a casa à nossa maneira ?

**Comment by miguelriemoliveira** [comment]
Sim, podem, desde que seja minimamente realista.
