### ISSUE TITLE
psr apartment, com falta de objetos

### ISSUE THREAD

**Issue by jgvf** [miguelriemoliveira/psr_22-23#17]
Estou a usar a pasta psr_apartement_description e o mundo psr_apartment.world. E deparei-me que ao abrir o gazebo, parte dos abjetos não aparecem.
Imagem que me aparece:

![Screenshot from 2023-01-28 15-28-37](https://user-images.githubusercontent.com/116443385/215275113-26893656-cf5b-4afd-a56a-c2ed923ee753.png)

Imagem que devia aparecer:

![image](https://user-images.githubusercontent.com/116443385/215274933-95502110-3bdf-42f5-8f1f-f7f56ccb7503.png)

Na aula gravada "Aula 11 P1 - PSR 2022-2023", usou o seguinte gazebo.launch.
![Screenshot from 2023-01-28 15-35-43](https://user-images.githubusercontent.com/116443385/215275365-7c410fe3-0a9d-4e4f-a1d0-da559eb97b2f.png)

e eu estou a usar o seguinte:

![Screenshot from 2023-01-28 15-37-16](https://user-images.githubusercontent.com/116443385/215275424-b7c82017-d7e0-4270-a99e-037e98795ef9.png)

Não estou a perceber estes resultados diferentes!

**Comment by miguelriemoliveira** [comment]
Olá @jgvf ,

não copie um printscreen do código, copie o texto do código. É mais fácil de ver, copiar e adaptar.

Quanto à pergunta: o objetivo de utilizar os issues é que quando se responde a uma pergunta a resposta fica disponível para todos. Para que isto funcione, antes de fazer uma pergunta, devemos procurar nos issues já existentes se há alguma pergunta  igual à nossa, que até já pode estar respondida.

Neste caso acho pode ver que o issue #12 é exatamente o seu problema.
Veja o que lá está e se depois precisar de mais ajuda diga.
