### ISSUE TITLE
problemas a guardar o mapa

### ISSUE THREAD

**Issue by jgvf** [miguelriemoliveira/psr_22-23#18]
Estou a tentar guardar o mapa que mapeei e apareceu-se o seguinte erro:
[rospack] Error: package 'map_server' not found
E instalei o mapserver e o erro passou para:
E: Unable to locate package ros-noetic-mapserver 
O que devo fazer?

**Comment by miguelriemoliveira** [comment]
Como fez a instalação do map_server?

**Comment by jgvf** [comment]
sudo apt-get install ros-noetic-mapserver
Mas continuou a dar erro e experimentei outro comandos, usei este link como referencia, https://answers.ros.org/question/233257/rospack-error-package-map_server-not-found/.

**Comment by miguelriemoliveira** [comment]
Quando faz 

    sudo apt-get install ros-noetic-mapserver

qual é o output do terminal?

Consegue fazer 

    roscd mapserver

?

Tem o ROS devidamente configurado? Por exemplo, consegue fazer 

    roscd tf

?

**Comment by jgvf** [comment]
O output do terminal é:
[sudo] password for joao: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-noetic-mapserver

Quando faço, roscd mapserver:
roscd: No such package 'mapserver'

quando faço,roscd tf, vai para a pasta tf.

**Comment by miguelriemoliveira** [comment]
Olá @jgvf ,

e com esse output, acha que o mapserver foi instalado?

**Comment by miguelriemoliveira** [comment]
O problema é que não está a conseguir instalar o map server.

Já fez o sudo 

    apt-get update

Qual o output?

**Comment by jgvf** [comment]
[sudo] password for joao: 
Hit:1 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:2 http://archive.canonical.com/ubuntu focal InRelease                      
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                         
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Hit:5 http://packages.microsoft.com/repos/code stable InRelease
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [59,9 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [93,9 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [940 B]
Hit:9 http://packages.ros.org/ros/ubuntu focal InRelease                 
Hit:10 http://pt.archive.ubuntu.com/ubuntu focal InRelease
Hit:11 http://pt.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:12 http://pt.archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 269 kB in 6s (48,1 kB/s)
Reading package lists... Done

**Comment by jgvf** [comment]
E au tentar instalar novamente com esse comando sai:
➜  ~ sudo apt-get install ros-noetic-mapserver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-noetic-mapserver

**Comment by miguelriemoliveira** [comment]
não vejo em lado nenhum repositórios com o ros.

Tem a certeza que instalou o ros com estas instruções?

http://wiki.ros.org/noetic/Installation/Ubuntu

Em particular os pontos 1.2 e 1.3.

**Comment by jgvf** [comment]
Eu segui o procedimento que lá estava no video mas n estava a conceguir e que me conceguiu instalar foi o Bruno. Que eu lançei esse comandos lancei, agóra se fez o que éra pretendido n faço ideia.

**Comment by jgvf** [comment]
faltavam-me coisas no .zshrc, por isso é que n estava a dar.

**Comment by miguelriemoliveira** [comment]
Ah. Está explicado.

Se está resolvido pff feche o issue.

**Comment by jgvf** [comment]
Estou a falar que ficou resolvido o questão da instalação do ros, ficou a funcionar.
Esta questão do mapserver ainda n esta resolvida.

**Comment by miguelriemoliveira** [comment]
> Estou a falar que ficou resolvido o questão da instalação do ros, ficou a funcionar.
> Esta questão do mapserver ainda n esta resolvida.

Hum, mas a instalação do ROS não está correta porque quando fez 

    sudo apt-get update 

não aparece nenhum repositório do ROS. Repita todas as instruções em 

http://wiki.ros.org/noetic/Installation/Ubuntu

Para ver se depois consegue instalar o mapserver.

**Comment by jgvf** [comment]
okay! Neste momento o ros já não está a funcionar novamente! 
Experimentei fazer:
➜  ~ roslaunch robutler_bringup gazebo.launch
RLException: [gazebo.launch] is neither a launch file in package [robutler_bringup] nor is [robutler_bringup] a launch file name
The traceback for the exception was written to the log file

**Comment by jgvf** [comment]
N sei o que fazer!

**Comment by miguelriemoliveira** [comment]
Acho que tem de instalar novamente como no link que enviei em cima. Siga todos os passos de instalação.

**Comment by jgvf** [comment]
Já está resolvido! Obrigado!
