### ISSUE TITLE
Duvida com o Timmer

### ISSUE THREAD

**Issue by jotadateta** [miguelriemoliveira/psr_22-23#3]
Professor nos estamos praticamente com tudo orientado no entanto temos um problema com o timer pois a função readkey() para-nos o codigo e como tal o programa nunca termina aos segundos determinados mas sim apos a ultima tecla clicada antes do timer terminar , na print colocamos um limite de 5 segundos para demostrar o nosso erro
![Screenshot from 2022-10-11 15-27-45](https://user-images.githubusercontent.com/100309502/195119523-0a0db16e-0d04-4ca2-a232-bba1c11ed8d1.png)

**Comment by jotadateta** [comment]
Envio tambem o repositorio se der jeito ao professor para perceber melhor 

https://github.com/jotadateta/PSR-2022-23/blob/master/main.py

**Comment by miguelriemoliveira** [comment]
Olá @jotadateta ,

Esse é o comportamento esperado.

Its a feature, not a bug.
