### ISSUE TITLE
Camera overexposure / color detected varying with distance.

### ISSUE THREAD

**Issue by brunofavs** [miguelriemoliveira/psr_22-23#4]
Hi,
I was about to finish the color_segmenter.py script, when I realized that my camera with distance overexposes the screen. So if i show the color close, it detects the color as it should, however if I bring my phone back, it reaches a point where it just registers white.
How can I work around this?

-I found that some cameras allow to cap exposure with cv2.CAP_PROP_EXPOSURE, however mine does not.
-I tried to reduce the brightness, but it doesn't make a difference.
-Tried with less satured colors, and less screen brightness.

With non screen objects, it works fine, but that kinda defeats the purpose of having a dedicated script to register different colors :c

![image](https://user-images.githubusercontent.com/31831043/197403611-8cc99906-61db-48a5-893a-694945422aee.png)
![image](https://user-images.githubusercontent.com/31831043/197403673-4e6b7700-ffd4-4143-8d82-3fb00138453d.png)

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

>  it reaches a point where it just registers white.

I do not understand very well what this means. Can you explain?

> With non screen objects, it works fine,

Also, what is a non screen object?

Sorry, but I need to understand if I am going to be able to help.

**Comment by brunofavs** [comment]
Hi,

I'd like to note first that in both photos the color selected on my phone is the same pink.

Adressing your first point:
-    In the first image where my face is, the phone screen appears to be white while its pink in reality, like shown in the second picture. This is happening because the screen is a intense source of light in a rather dim ambient. I had my curtains closed because otherwise its unbearable  with a ton of reflections on the phone. If i were to open them, even though the reflections would make the situation worse, the screen's light intensity wouldnt contrast as much with the environment and the color wouldnt vary as much with distance.

Moving to your second point:
- By non screen object I mean really anything other than a screen. Say I bring for instance a red apple in my hands, it appears the same shade of red whether I hold it right next to the Webcam or far away.

**Comment by brunofavs** [comment]
This is really more of a optimization issue than anything else to be fair. I would like to see if I can minimize it nonetheless.

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

now I get it. Yes, its normal that the camera has problems with the screens. However, like you say, this is just an optimization.
If it works more or less well for a reasonable distance, don't worry about it and work on the rest.

**Comment by miguelriemoliveira** [comment]
To minimize this we would have to be able to change the camera's parameters.
