### ISSUE TITLE
How do I use roslaunch to run nodes at different terminals.

### ISSUE THREAD

**Issue by brunofavs** [miguelriemoliveira/psr_22-23#9]
For a simple example where I launch a publisher and a subscriber node with roslaunch, how do I forward the output to a different terminal?
I would like the roslaunch to split my terminal in 2 somehow and send the output to the corresponding terminal, like we did previously with rosrun.
With everything outputting to 1 terminal, it gets messy real fast :c

Example : 
![image](https://user-images.githubusercontent.com/31831043/201753059-8a167521-fc1c-49ae-a2d5-e2c3c9ba3669.png)

**Comment by miguelriemoliveira** [comment]
Hi Bruno,

You can create two separate roslaunch files.

You can also use rqt_console.
